### ISSUE TITLE
El marcador que hi ha a sota del "Em vull implicar" general no va bé, marca 6 quan haurien de ser 12.

### ISSUE THREAD

**Issue by perelosantos** [UPC/goteo-nexus24#13]
Pues eso, no sé què vol dir

**Comment by perelosantos** [comment]
![image](https://user-images.githubusercontent.com/38557230/40415228-b92f8006-5e7a-11e8-8020-01a68d90d1f9.png)

**Comment by alexm** [comment]
Crec que això passa quan un usuari fa diverses implicacions en un mateix projecte. El número total d'implicats en aquest cas és 12, però el número d'usuaris diferents que s'han implicat 6.

A la base de dades, els camps s'anomenen _amount_ (actualment 17) i _investors_ (actualment 6).
