### ISSUE TITLE
Configuració de campanya apareix PAYPAL, al menú del proposador de projecte

### ISSUE THREAD

**Issue by perelosantos** [UPC/goteo-nexus24#17]

**Comment by perelosantos** [comment]
![image](https://user-images.githubusercontent.com/38557230/40841632-68b3da0e-65ab-11e8-8630-0e3d11f1f3b2.png)

**Comment by alexm** [comment]
Resolt amb el canvi https://github.com/UPC/goteo/commit/a809f4c3c1e13a7353a11607788c080f4250c8c5.
