### ISSUE TITLE
Eliminar les FAQ del menú.

### ISSUE THREAD

**Issue by perelosantos** [UPC/goteo-nexus24#18]
Les FAQ encara no estan clares i t'envien a la pàgina principal de goteo, queda malament i tampoc no ajuden. Si es poden desactivar del menú superior dreta, millor.

**Comment by alexm** [comment]
El canvi https://github.com/UPC/goteo/commit/fd2b5cd7d5091e40ebcd08c54af313be4fb8fdc8 elimina les FAQ del menú principal.
