### ISSUE TITLE
LDAP o login GOTEO

### ISSUE THREAD

**Issue by perelosantos** [UPC/goteo-nexus24#3]
Sí, si accedeixes des de la barra superior vas al LDAP, però si vols fer M'hi implico des de qualsevol botó va al registre del goteo. En canvi si vas al "m'agrada" (el like, a sota del botó principal) sí que va a LDAP. Entro això al github?

**Comment by alexm** [comment]
Ja he fet el canvi perquè el login vagi al CAS i el signup doni un error en cas que algú provés de posar la URL a mà. Ho he provat les dues URL de més amunt i crec que funciona correctament. Pots confirmar que també et funciona bé, @perelosantos?

**Comment by perelosantos** [comment]
![image](https://user-images.githubusercontent.com/38557230/40355238-2d2b1eea-5db6-11e8-9d26-e5b2b71aa561.png)
Potser queda canviar el text perquè digui que ha d'accedir via login de dalt a la dreta.

**Comment by alexm** [comment]
Aquest és un error del sistema per als usuaris espabilats que provin la URL de signup directament, sense clicar enlloc. Ara que ho he corregit, ja no hi ha cap enllaç per al signup quan el CAS està activat perquè no es pot fer signup al CAS, per tant ja no hauria d'afectar a cap usuari normal.

Diguem que és una mesura de prevenció contra els espabilats enlloc de donar una pàgina inexistent i per tant, crec que no té sentit explicar-ho amb més detall.

Si et sembla bé, ho donaré per resolt.
