### ISSUE TITLE
Fer desaparèixer total o parcialment pas 2 del pagament

### ISSUE THREAD

**Issue by perelosantos** [UPC/goteo-nexus24#4]
A https://nexus24.dakara.ac.upc.edu/invest/biodiversitat-upc/payment?reward=38&amount=1 apareixen dues opcions a sota
- anònim
- Vull que la meva donació, en el cas que el projecte no arribi al seu objectiu, romangui al meu moneder virtual Goteo. Més informació

El segon hauria de desaparèixer, de fet podria desaparèixer tot el pas sencer perquè no volem que sigui anònima.

**Comment by alexm** [comment]
He integrat els canvis a la branca *dakara* del meu _fork_:

* https://github.com/alexm/goteo/commit/3bd3ff0a6cb316cd53ac6fb0adde60ef1f292c2f
* https://github.com/alexm/goteo/commit/e4bc01e8dd058e40e464fd3a83ff16ff282f6cef

La integració de tot plegat al plugin encara trigarà un temps, així que dono per resolta la tasca.
