### ISSUE TITLE
Del resum del projecte que surt a sota de cada node eliminar la 4a dada, la dels diners recaptats

### ISSUE THREAD

**Issue by perelosantos** [UPC/goteo-nexus24#6]

**Comment by perelosantos** [comment]
![image](https://user-images.githubusercontent.com/38557230/40225561-a64f57ee-5a89-11e8-9104-42d5da4a11f0.png)

**Comment by perelosantos** [comment]
Això només te sentit quan diners i persones que aporten són diferents, però aquí cada persona és una moneda, i no té massa sentit. A més cal canviar el text, això suposo que ho puc fer jo.

**Comment by alexm** [comment]
Es pot configurar des del menú `Admin » Elementos en portada » Elementos en portada`, tant per al node/canal central com per a tota la resta. De moment ho desactivem i llestos.
