### ISSUE TITLE
Eliminar el login (Registre) i deixar només accés via LDAP

### ISSUE THREAD

**Issue by perelosantos** [UPC/goteo-nexus24#7]
Això passa quan vas a un canal determinat, diu que CAS està activat i no deixa fer registre ni ens interessa

**Comment by perelosantos** [comment]
![image](https://user-images.githubusercontent.com/38557230/40230162-de060392-5a96-11e8-886b-d81486b7978b.png)

**Comment by alexm** [comment]
El canvi https://github.com/UPC/goteo/commit/b083a4ade1c1ba852f2fd735703e22e4a3a2f81b elimina aquest enllaç.

**Comment by alexm** [comment]
El canvi https://github.com/UPC/goteo/commit/a324de270e3ff909bac1a728584e55c3900aa20f complementa l'anterior i evita que salti el missatge d'error del signup al CAS.
