### ISSUE TITLE
Canviar nivells de meritocràcia en català

### ISSUE THREAD

**Issue by perelosantos** [UPC/goteo-nexus24#9]
En castellà no he tingut problema però en català no puc de moment

**Comment by perelosantos** [comment]
Hola @microstudi tens solució per aquest tema de la meritocràcia en català?

**Comment by microstudi** [comment]
A si, aixo es tradueix al panell de traducció:

URL/translate/worthcracy

Per cert (si teniu de les últimes versions de goteo) que desde aquest panell també es pot desar la versió del idioma per defecte (castellà a menys que sigueu molt atrevits). O sigui que ho podeu editar gairebé tot allà.

Si no veieu el panell de traducció us heu d'assignar el rol de "traductor" amb els idiomes corresponents

**Comment by perelosantos** [comment]
Normalment funciona el que dius, però aquest cop no. Amb goteo en castellà em surt el que li he posat com a català (primer cop, dos cops...) i quan poso en català apareix el que no vull (fan... visionario)
CAT
![image](https://user-images.githubusercontent.com/38557230/40419968-2945dece-5e87-11e8-984f-5471c7047a1b.png)
ES
![image](https://user-images.githubusercontent.com/38557230/40420002-3d2541d2-5e87-11e8-8758-ba7c85dc9e8f.png)

**Comment by perelosantos** [comment]
Potser he d'esborrar tot, no ho sé. El tema és que no apareix al traductor la versió ES

**Comment by microstudi** [comment]
potser hi ha un bug en la gestió per aquesta taula.
Aqui tampoc et funciona?

URL/admin/worth

**Comment by perelosantos** [comment]
No. té pinta que s'ha fet un embolic perquè el ES ha desaparegut de la traducció.

**Comment by perelosantos** [comment]
Els valors de meritocràcia sí funcionen, però els noms del català no els puc canviar de cap manera

**Comment by microstudi** [comment]
I que surt en l'ultim link que t'he passat? el valors originals, fan, patrocinador, etc?
quan dius que no funciona vols dir que ho canvies i no et fa cas o una altra cosa?

Una altra cosa, al vostre settings.yml a quin valor teniu la variable `sql_lang`?

**Comment by perelosantos** [comment]
Quan sóc a ES sí canvia i fa el que li dic, 
![image](https://user-images.githubusercontent.com/38557230/40421198-48e45162-5e8b-11e8-8d3a-e2ad4f433015.png)
Això li demano
![image](https://user-images.githubusercontent.com/38557230/40421234-6c69bd02-5e8b-11e8-81a8-e1d1a0e2e37f.png)
I si el vull canviar va a Nivel2 (que no sé què és) i es deixa canviar
![image](https://user-images.githubusercontent.com/38557230/40421272-9b3ca216-5e8b-11e8-90fe-ba9c87f45989.png)

**Comment by perelosantos** [comment]
Però quan vaig a CAT ja veig això
![image](https://user-images.githubusercontent.com/38557230/40421293-b0864cf8-5e8b-11e8-8f6c-1f0347f881b1.png)

i si vaig a l'admin en CAT em diu això
![image](https://user-images.githubusercontent.com/38557230/40421321-d05e81a8-5e8b-11e8-9cdb-3294d04efa4b.png)

i si els provo d'editar em diu 
![image](https://user-images.githubusercontent.com/38557230/40421350-eb38e18a-5e8b-11e8-95c0-c2b2ddb3b37d.png)

És com si anés a la mateixa pàgina d'ES.

**Comment by perelosantos** [comment]
I no em deixa marcar "pendiente de traducir", potser no té ES a la taula de traducció o hem esborrat massa coses, ni idea.

**Comment by microstudi** [comment]
està clar que hi ha un bug en el model que mostra les dades.
El més senzill (si no ho heu de tocar gaires vegades) es fer-ho directament a la base de dades, si pot ser poseu el bug als issues del github de goteo i així quan pugui l'arreglo.

Si voleu tocar la base de dades, les taules implicades son:

`worthcrazy`
`worthcrazy_lang`

La segona son les traduccions (que si la variable `sql_lang` està a 'es', cosa que recomano) on estan tots els idiomes sense el castellà. El castellà a la primera.

**Comment by alexm** [comment]
@perelosantos Ja he aplicat els canvis a la nostra instància de prova i ja es poden traduir les cadenes de meritocràcia via https://nexus24.dakara.ac.upc.edu/translate/worthcracy.
